import type { Metadata } from "next";
import "../globals.css";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Onetech",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <head>
      {/* Google tag (gtag.js) */}
      <Script
        src="https://www.googletagmanager.com/gtag/js?id=G-Y263EXQ6JJ"
        strategy="afterInteractive"
      />
      <Script id="google-analytics" strategy="afterInteractive">
        {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-Y263EXQ6JJ');
          `}
      </Script>
    </head>
    <body>
    {children}
    </body>
    </html>
  );
}
